name: DebugBuild

#実行する場所(今回はmasterブランチにプッシュされたとき)
on:
 push:
  branches:
   -master
#何をビルドするのか
env:
 #リポジトリのルートディレクトリを基点としたソリューションファイルのパス
 SOLUTION_FILE_PATH: project/CG2.sln
 #Visual Studio の構成(今回はデバッグ)
 CONFIGURATION:CONFIGURATION: Debug
#何をするのか(今回はビルド)
jobs:
 build:
  runs-on: windows-2022

  steps:
   - name: Checkout
     uses: actions/checkout@v4
   - name: Add MSBuild to PATH
     uses: microsoft/setup-msbuild@v2
     with:
      msbuild-architecture: x64
   - name: Build
     run:
      msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}



      
